# Generated by Django 3.1.6 on 2021-04-22 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(choices=[(False, 'Student'), (True, 'Teacher')], default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('emailID', models.EmailField(blank=True, max_length=50, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_one.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('emailID', models.EmailField(blank=True, max_length=50, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_one.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz1', models.FloatField(default=0)),
                ('quiz2', models.FloatField(default=0)),
                ('mst', models.FloatField(default=0)),
                ('est', models.FloatField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Course_teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Course_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(choices=[(True, 'Present'), (False, 'Absent')])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.studentinfo')),
            ],
        ),
    ]
