# Generated by Django 3.1.6 on 2021-04-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20210407_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='dob',
        ),
    ]
