# Generated by Django 3.1.6 on 2021-04-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0007_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Mark',
        ),
    ]
