# Generated by Django 3.1.6 on 2021-04-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0009_course_taken_course_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_teaching',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_one.teacherinfo'),
        ),
    ]
