# Generated by Django 3.1.6 on 2021-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0010_auto_20210412_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
