# Generated by Django 3.1.6 on 2021-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0011_auto_20210422_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
